# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Coveralls

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coveralls:

    runs-on: ubuntu-latest

    steps:
    - name: Cloning repo
      uses: actions/checkout@v3
    - name: Use Node.js 15.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Installing dependences
      run: npm install
    - name: Generating coverage information
      run: npm run coverage
    - name: Coveralls GitHub Actions
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}